[server]
headless = true
enableCORS = false
port = 8501

[theme]
base = "light"
primaryColor = "#4285F4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"
